name: On Schedule process

on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

jobs:
  hello-world:
    name: fetch_new_signs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Execute script
        run: python code/process_new_signs.py
        shell: sh